[ethereum]
endpoint = "wss://kovan.infura.io/ws/v3/3592e9c20d9b4169a394a608a310c85f"

[ethereum.bridge]
address = "0xb9A469F82C1c39a3A4BCE872adA6297f8d697A8a"
abi = "/tmp/contracts/Bridge.json"

[ethereum.apps.eth]
address = "0xF6c4D8E8C65c267bFADE16A95978Da85743C950D"
abi = "/tmp/contracts/ETHApp.json"

[ethereum.apps.erc20]
address = "0x24FC6d717C4864BEE368e63dE9edb5276C263F7a"
abi = "/tmp/contracts/ERC20App.json"

[substrate]
endpoint = "ws://mangata-node:9944/"
